#version: "1.29.2"

services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-zycxl)x2izh11t%brm^b6hpu=!*%098(j0t1sr8&sekpbil@4e
      - DEBUG=True
      #- ALLOWED_HOSTS = *

