
services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./core:/code
    ports:
      - "8000:8000"
    environment:
      - SECRT_KEY=django-insecure-k48@n=z$oe5z*$q!d+e6+@k8#(pezb=9!c_$z8(nf+bw$#$gni
      - DEBUG=True